name: CI/CD Pipeline for AnalytiCore

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar QEMU y Buildx para multiarquitectura
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Iniciar sesión en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construir y empujar la imagen del Servicio de Submisión
      - name: Build and push submission-service
        uses: docker/build-push-action@v5
        with:
          context: ./python-service
          file: ./python-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-submission-service:latest

      # Construir y empujar la imagen del Servicio de Análisis
      - name: Build and push analysis-service
        uses: docker/build-push-action@v5
        with:
          context: ./java-service
          file: ./java-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/analysis-service:latest

      # Desplegar en Render (Servicio de Submisión)
      - name: Deploy to Render - Submission Service
        uses: rendercom/render-action@v1
        with:
          service-id: ${{ secrets.RENDER_SUBMISSION_SERVICE_ID }}
          api-token: ${{ secrets.RENDER_API_TOKEN }}

      # Desplegar en Render (Servicio de Análisis)
      - name: Deploy to Render - Analysis Service
        uses: rendercom/render-action@v1
        with:
          service-id: ${{ secrets.RENDER_ANALYSIS_SERVICE_ID }}
          api-token: ${{ secrets.RENDER_API_TOKEN }}